//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminPanel.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Index {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Index() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AdminPanel.Resources.Index", typeof(Index).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kurumsal.
        /// </summary>
        public static string AboutUss {
            get {
                return ResourceManager.GetString("AboutUss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İşlemler.
        /// </summary>
        public static string Actions {
            get {
                return ResourceManager.GetString("Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ekle.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yeni Galeri Ekle.
        /// </summary>
        public static string AddGallery {
            get {
                return ResourceManager.GetString("AddGallery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Galeri Kategorisi Ekle.
        /// </summary>
        public static string AddGalleryCategory {
            get {
                return ResourceManager.GetString("AddGalleryCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Galeri Fotoğrafı ekle.
        /// </summary>
        public static string AddGalleryPhoto {
            get {
                return ResourceManager.GetString("AddGalleryPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yeni Kategori Ekle.
        /// </summary>
        public static string AddNewCategory {
            get {
                return ResourceManager.GetString("AddNewCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yeni Galeri Ekle.
        /// </summary>
        public static string AddNewGallery {
            get {
                return ResourceManager.GetString("AddNewGallery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yeni Galeri Kategorisi Ekle.
        /// </summary>
        public static string AddNewGalleryCategory {
            get {
                return ResourceManager.GetString("AddNewGalleryCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yeni Haber Ekle.
        /// </summary>
        public static string AddNewNews {
            get {
                return ResourceManager.GetString("AddNewNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yeni Sayfa Ekle.
        /// </summary>
        public static string AddNewPage {
            get {
                return ResourceManager.GetString("AddNewPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yeni Partner Ekle.
        /// </summary>
        public static string AddNewPartner {
            get {
                return ResourceManager.GetString("AddNewPartner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yeni Ürün Ekle.
        /// </summary>
        public static string AddNewProduct {
            get {
                return ResourceManager.GetString("AddNewProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yeni Referans Ekle.
        /// </summary>
        public static string AddNewReference {
            get {
                return ResourceManager.GetString("AddNewReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yeni Referans Kategorisi Ekle.
        /// </summary>
        public static string AddNewReferenceCategory {
            get {
                return ResourceManager.GetString("AddNewReferenceCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Haber Ekle.
        /// </summary>
        public static string AddNews {
            get {
                return ResourceManager.GetString("AddNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yeni Hizmet Ekle.
        /// </summary>
        public static string AddNewService {
            get {
                return ResourceManager.GetString("AddNewService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yeni Slider Ekle.
        /// </summary>
        public static string AddNewSlider {
            get {
                return ResourceManager.GetString("AddNewSlider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yeni Slider Kategorisi Ekle.
        /// </summary>
        public static string AddNewSliderCategory {
            get {
                return ResourceManager.GetString("AddNewSliderCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yeni Personel Ekle.
        /// </summary>
        public static string AddNewStaff {
            get {
                return ResourceManager.GetString("AddNewStaff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yeni Personel Görevi Ekle.
        /// </summary>
        public static string AddNewStaffPosition {
            get {
                return ResourceManager.GetString("AddNewStaffPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sayfa Ekle.
        /// </summary>
        public static string AddPage {
            get {
                return ResourceManager.GetString("AddPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ürün Ekle.
        /// </summary>
        public static string AddProduct {
            get {
                return ResourceManager.GetString("AddProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Referans Ekle.
        /// </summary>
        public static string AddReference {
            get {
                return ResourceManager.GetString("AddReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Referans Kategorisi Ekle.
        /// </summary>
        public static string AddReferenceCategory {
            get {
                return ResourceManager.GetString("AddReferenceCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yeni Hizmet Ekle.
        /// </summary>
        public static string AddServices {
            get {
                return ResourceManager.GetString("AddServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hizmet Resimleri Yükle.
        /// </summary>
        public static string AddServicesPhotos {
            get {
                return ResourceManager.GetString("AddServicesPhotos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slider Ekle.
        /// </summary>
        public static string AddSlider {
            get {
                return ResourceManager.GetString("AddSlider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slider Kateogiri Ekle.
        /// </summary>
        public static string AddSliderCategory {
            get {
                return ResourceManager.GetString("AddSliderCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personel Ekle.
        /// </summary>
        public static string AddStaff {
            get {
                return ResourceManager.GetString("AddStaff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personel Grrevi Ekle.
        /// </summary>
        public static string AddStaffPosition {
            get {
                return ResourceManager.GetString("AddStaffPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Satılık Asp.Net Admin Panel.
        /// </summary>
        public static string AspNetAdminPanelOnSale {
            get {
                return ResourceManager.GetString("AspNetAdminPanelOnSale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kategori Adı.
        /// </summary>
        public static string CategoryName {
            get {
                return ResourceManager.GetString("CategoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İngilizce Kategori Adı.
        /// </summary>
        public static string CategoryNameEN {
            get {
                return ResourceManager.GetString("CategoryNameEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Türkçe Kategori Adı.
        /// </summary>
        public static string CategoryNameTR {
            get {
                return ResourceManager.GetString("CategoryNameTR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kategori Seç.
        /// </summary>
        public static string ChoseCategory {
            get {
                return ResourceManager.GetString("ChoseCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personel Görevi Seç.
        /// </summary>
        public static string ChoseStaffPosition {
            get {
                return ResourceManager.GetString("ChoseStaffPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temizle.
        /// </summary>
        public static string Clean {
            get {
                return ResourceManager.GetString("Clean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dili seçmek için tıklayın.
        /// </summary>
        public static string ClicktochoseLanguage {
            get {
                return ResourceManager.GetString("ClicktochoseLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kapalı.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firma Adresi.
        /// </summary>
        public static string CompanyAddress {
            get {
                return ResourceManager.GetString("CompanyAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firma Email.
        /// </summary>
        public static string CompanyEmail {
            get {
                return ResourceManager.GetString("CompanyEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firma Facebook Adresi.
        /// </summary>
        public static string CompanyFacebook {
            get {
                return ResourceManager.GetString("CompanyFacebook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firma Linkedin.
        /// </summary>
        public static string CompanyLinkedin {
            get {
                return ResourceManager.GetString("CompanyLinkedin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firma Adı.
        /// </summary>
        public static string CompanyName {
            get {
                return ResourceManager.GetString("CompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firma Telefon.
        /// </summary>
        public static string CompanyPhone {
            get {
                return ResourceManager.GetString("CompanyPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firma Skype.
        /// </summary>
        public static string CompanySkype {
            get {
                return ResourceManager.GetString("CompanySkype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firma Twitter Adresi.
        /// </summary>
        public static string CompanyTwitter {
            get {
                return ResourceManager.GetString("CompanyTwitter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parolayı Onayla.
        /// </summary>
        public static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İletişim.
        /// </summary>
        public static string Contact {
            get {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mesaj.
        /// </summary>
        public static string ContactMessage {
            get {
                return ResourceManager.GetString("ContactMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İletişim Mesajları.
        /// </summary>
        public static string ContactMessages {
            get {
                return ResourceManager.GetString("ContactMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright.
        /// </summary>
        public static string Copyright {
            get {
                return ResourceManager.GetString("Copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Bulunamadı.
        /// </summary>
        public static string DataNotFound {
            get {
                return ResourceManager.GetString("DataNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sil.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kategori Sil.
        /// </summary>
        public static string DeleteCategory {
            get {
                return ResourceManager.GetString("DeleteCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Galeri Sil.
        /// </summary>
        public static string DeleteGallery {
            get {
                return ResourceManager.GetString("DeleteGallery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Galeri Kategorisi Sil.
        /// </summary>
        public static string DeleteGalleryCategory {
            get {
                return ResourceManager.GetString("DeleteGalleryCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Haber Sil.
        /// </summary>
        public static string DeleteNews {
            get {
                return ResourceManager.GetString("DeleteNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sayfa Sil.
        /// </summary>
        public static string DeletePage {
            get {
                return ResourceManager.GetString("DeletePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partner Sil.
        /// </summary>
        public static string DeletePartner {
            get {
                return ResourceManager.GetString("DeletePartner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ürün Sil.
        /// </summary>
        public static string DeleteProduct {
            get {
                return ResourceManager.GetString("DeleteProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Reference.
        /// </summary>
        public static string DeleteReference {
            get {
                return ResourceManager.GetString("DeleteReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Referans Kategorisi Sil.
        /// </summary>
        public static string DeleteReferenceCategory {
            get {
                return ResourceManager.GetString("DeleteReferenceCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hizmet Sil.
        /// </summary>
        public static string DeleteServices {
            get {
                return ResourceManager.GetString("DeleteServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slider Sil.
        /// </summary>
        public static string DeleteSlider {
            get {
                return ResourceManager.GetString("DeleteSlider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slider Kategori Sil.
        /// </summary>
        public static string DeleteSliderCategory {
            get {
                return ResourceManager.GetString("DeleteSliderCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personel Sil.
        /// </summary>
        public static string DeleteStaff {
            get {
                return ResourceManager.GetString("DeleteStaff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personel Görevi Sil.
        /// </summary>
        public static string DeleteStaffPosition {
            get {
                return ResourceManager.GetString("DeleteStaffPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Düzenle.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kategori Düzenle.
        /// </summary>
        public static string EditCategory {
            get {
                return ResourceManager.GetString("EditCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Galeri Düzenle.
        /// </summary>
        public static string EditGallery {
            get {
                return ResourceManager.GetString("EditGallery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Galeri Kategorisi Düzenle.
        /// </summary>
        public static string EditGalleryCategory {
            get {
                return ResourceManager.GetString("EditGalleryCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Haber Düzenle.
        /// </summary>
        public static string EditNews {
            get {
                return ResourceManager.GetString("EditNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sayfa Düzenle.
        /// </summary>
        public static string EditPage {
            get {
                return ResourceManager.GetString("EditPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partner Düzenle.
        /// </summary>
        public static string EditPartner {
            get {
                return ResourceManager.GetString("EditPartner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ürün Düzenle.
        /// </summary>
        public static string EditProduct {
            get {
                return ResourceManager.GetString("EditProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Reference.
        /// </summary>
        public static string EditReference {
            get {
                return ResourceManager.GetString("EditReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Referans Kategorisi Düzenle.
        /// </summary>
        public static string EditReferenceCategory {
            get {
                return ResourceManager.GetString("EditReferenceCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hizmet Düzenle.
        /// </summary>
        public static string EditServices {
            get {
                return ResourceManager.GetString("EditServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slider Düzenle.
        /// </summary>
        public static string EditSlider {
            get {
                return ResourceManager.GetString("EditSlider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slider Kategori Düzenle.
        /// </summary>
        public static string EditSliderCategory {
            get {
                return ResourceManager.GetString("EditSliderCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personel Düzenle.
        /// </summary>
        public static string EditStaff {
            get {
                return ResourceManager.GetString("EditStaff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personel Görevi Düzenle.
        /// </summary>
        public static string EditStaffPosition {
            get {
                return ResourceManager.GetString("EditStaffPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İngilizce.
        /// </summary>
        public static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İngilizce Galeri Adı.
        /// </summary>
        public static string EnglishGalleryName {
            get {
                return ResourceManager.GetString("EnglishGalleryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İngilizce Haber Açklaması.
        /// </summary>
        public static string EnglishNewsContent {
            get {
                return ResourceManager.GetString("EnglishNewsContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İngilizce Haber Başlığı.
        /// </summary>
        public static string EnglishNewsTitle {
            get {
                return ResourceManager.GetString("EnglishNewsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İngilizce Sayfa İçeriği.
        /// </summary>
        public static string EnglishPageContent {
            get {
                return ResourceManager.GetString("EnglishPageContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İngilizce Sayfa Başluğı.
        /// </summary>
        public static string EnglishPageTitle {
            get {
                return ResourceManager.GetString("EnglishPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İngilizce Ürün Açıklaması.
        /// </summary>
        public static string EnglishProductDescription {
            get {
                return ResourceManager.GetString("EnglishProductDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İngilizce Ürün Adı.
        /// </summary>
        public static string EnglishProductName {
            get {
                return ResourceManager.GetString("EnglishProductName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İngilizce Referans Açıklaması.
        /// </summary>
        public static string EnglishReferenceDescription {
            get {
                return ResourceManager.GetString("EnglishReferenceDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İngilizce Referans Başlığı.
        /// </summary>
        public static string EnglishReferenceTitle {
            get {
                return ResourceManager.GetString("EnglishReferenceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İngilizce Hizmet Acıklaması.
        /// </summary>
        public static string EnglishServiceDescription {
            get {
                return ResourceManager.GetString("EnglishServiceDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İngilizce Hizmet Başlığı.
        /// </summary>
        public static string EnglishServicesTitle {
            get {
                return ResourceManager.GetString("EnglishServicesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İngilizce Slider Başlığı.
        /// </summary>
        public static string EnglishSliderName {
            get {
                return ResourceManager.GetString("EnglishSliderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Galeri.
        /// </summary>
        public static string Gallery {
            get {
                return ResourceManager.GetString("Gallery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Galeri Kategorisi.
        /// </summary>
        public static string GalleryCategory {
            get {
                return ResourceManager.GetString("GalleryCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Galeri Kategori Listesi.
        /// </summary>
        public static string GalleryCategoryList {
            get {
                return ResourceManager.GetString("GalleryCategoryList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Galeri Listesi.
        /// </summary>
        public static string GalleryList {
            get {
                return ResourceManager.GetString("GalleryList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Galeri Adı.
        /// </summary>
        public static string GalleryName {
            get {
                return ResourceManager.GetString("GalleryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Galeri Fotoğrafı.
        /// </summary>
        public static string GallleryPhoto {
            get {
                return ResourceManager.GetString("GallleryPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Genel Ayarlar.
        /// </summary>
        public static string GeneralSettings {
            get {
                return ResourceManager.GetString("GeneralSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Genel Site Ayarları.
        /// </summary>
        public static string GeneralSiteSettings {
            get {
                return ResourceManager.GetString("GeneralSiteSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anasayfa.
        /// </summary>
        public static string HomePage {
            get {
                return ResourceManager.GetString("HomePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keywords.
        /// </summary>
        public static string Keywords {
            get {
                return ResourceManager.GetString("Keywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Çıkış yapılıyor lütfen bekleyiniz.
        /// </summary>
        public static string LoggingoutPleaseWait {
            get {
                return ResourceManager.GetString("LoggingoutPleaseWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giriş Yap.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İşlem yapmak için giriş yapınız.
        /// </summary>
        public static string Logintostartyoursession {
            get {
                return ResourceManager.GetString("Logintostartyoursession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Çıkış Yap.
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adı Soyad.
        /// </summary>
        public static string NameSurname {
            get {
                return ResourceManager.GetString("NameSurname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Haberler.
        /// </summary>
        public static string News {
            get {
                return ResourceManager.GetString("News", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Haber Tarihi.
        /// </summary>
        public static string NewsDate {
            get {
                return ResourceManager.GetString("NewsDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Haber Görseli.
        /// </summary>
        public static string NewsImage {
            get {
                return ResourceManager.GetString("NewsImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Haber Listesi.
        /// </summary>
        public static string NewsList {
            get {
                return ResourceManager.GetString("NewsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bildiriminiz.
        /// </summary>
        public static string notifications {
            get {
                return ResourceManager.GetString("notifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bildiriminiz var.
        /// </summary>
        public static string notificationsyouhave {
            get {
                return ResourceManager.GetString("notificationsyouhave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Açık.
        /// </summary>
        public static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sayfa İçeriği.
        /// </summary>
        public static string PageContent {
            get {
                return ResourceManager.GetString("PageContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sayfa Görselleri.
        /// </summary>
        public static string PageImages {
            get {
                return ResourceManager.GetString("PageImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sayfa Yönetimi.
        /// </summary>
        public static string PageManagement {
            get {
                return ResourceManager.GetString("PageManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sayfalar.
        /// </summary>
        public static string Pages {
            get {
                return ResourceManager.GetString("Pages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sayfa Listesi.
        /// </summary>
        public static string PagesList {
            get {
                return ResourceManager.GetString("PagesList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sayfa Yönetimi.
        /// </summary>
        public static string PagesManagement {
            get {
                return ResourceManager.GetString("PagesManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sayfa Başlığı.
        /// </summary>
        public static string PageTitle {
            get {
                return ResourceManager.GetString("PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sayfa Url.
        /// </summary>
        public static string PageUrl {
            get {
                return ResourceManager.GetString("PageUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logo.
        /// </summary>
        public static string PartnerLogo {
            get {
                return ResourceManager.GetString("PartnerLogo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Çözüm Ortağı Adı.
        /// </summary>
        public static string PartnerName {
            get {
                return ResourceManager.GetString("PartnerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Çözüm Ortakları.
        /// </summary>
        public static string Partners {
            get {
                return ResourceManager.GetString("Partners", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Çözüm Ortakları Listesi.
        /// </summary>
        public static string PartnersList {
            get {
                return ResourceManager.GetString("PartnersList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parola.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen bütün gerekli alanları doldurunuz hatta hepsini.
        /// </summary>
        public static string Pleasefillallrequiredfields {
            get {
                return ResourceManager.GetString("Pleasefillallrequiredfields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen Seçiniz.
        /// </summary>
        public static string PleaseSelect {
            get {
                return ResourceManager.GetString("PleaseSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ürün Kategori Fotoğrafı.
        /// </summary>
        public static string ProductCategoryPhoto {
            get {
                return ResourceManager.GetString("ProductCategoryPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ürün Kodu.
        /// </summary>
        public static string ProductCode {
            get {
                return ResourceManager.GetString("ProductCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ürün Açıklaması.
        /// </summary>
        public static string ProductDescription {
            get {
                return ResourceManager.GetString("ProductDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ürün Listesi.
        /// </summary>
        public static string ProductList {
            get {
                return ResourceManager.GetString("ProductList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ürün Yönetim.
        /// </summary>
        public static string ProductManagement {
            get {
                return ResourceManager.GetString("ProductManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ürün Adı.
        /// </summary>
        public static string ProductName {
            get {
                return ResourceManager.GetString("ProductName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ürün Fotoğrafı.
        /// </summary>
        public static string ProductPhoto {
            get {
                return ResourceManager.GetString("ProductPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ürünler.
        /// </summary>
        public static string Products {
            get {
                return ResourceManager.GetString("Products", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ürün Kategorisi.
        /// </summary>
        public static string ProductsCategory {
            get {
                return ResourceManager.GetString("ProductsCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ürün Kategori Listesi.
        /// </summary>
        public static string ProductsCategoryList {
            get {
                return ResourceManager.GetString("ProductsCategoryList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ürün Url Adresi.
        /// </summary>
        public static string ProductUrl {
            get {
                return ResourceManager.GetString("ProductUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profil Fotoğrafı.
        /// </summary>
        public static string ProfilePhoto {
            get {
                return ResourceManager.GetString("ProfilePhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profil Ayarları.
        /// </summary>
        public static string ProfileSettings {
            get {
                return ResourceManager.GetString("ProfileSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Referans Kategorisi.
        /// </summary>
        public static string ReferenceCategory {
            get {
                return ResourceManager.GetString("ReferenceCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Referans Kategori Listesi.
        /// </summary>
        public static string ReferenceCategoryList {
            get {
                return ResourceManager.GetString("ReferenceCategoryList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Referans Açıklaması.
        /// </summary>
        public static string ReferenceDescription {
            get {
                return ResourceManager.GetString("ReferenceDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Referans Logosu.
        /// </summary>
        public static string ReferenceLogo {
            get {
                return ResourceManager.GetString("ReferenceLogo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Referans Adı.
        /// </summary>
        public static string ReferenceName {
            get {
                return ResourceManager.GetString("ReferenceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Referenslar.
        /// </summary>
        public static string References {
            get {
                return ResourceManager.GetString("References", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Referans Listesi.
        /// </summary>
        public static string ReferencesList {
            get {
                return ResourceManager.GetString("ReferencesList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beni Hatırla.
        /// </summary>
        public static string RememberMe {
            get {
                return ResourceManager.GetString("RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kaydet.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bütün Mesajaları Gör.
        /// </summary>
        public static string SeeAllMessages {
            get {
                return ResourceManager.GetString("SeeAllMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bütün Bildirimleri Gör.
        /// </summary>
        public static string SeeAllNotification {
            get {
                return ResourceManager.GetString("SeeAllNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gönderen.
        /// </summary>
        public static string SenderName {
            get {
                return ResourceManager.GetString("SenderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hizmet Açıklaması.
        /// </summary>
        public static string ServiceDescription {
            get {
                return ResourceManager.GetString("ServiceDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hizmet Adı.
        /// </summary>
        public static string ServiceName {
            get {
                return ResourceManager.GetString("ServiceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hizmetler.
        /// </summary>
        public static string Services {
            get {
                return ResourceManager.GetString("Services", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hizmet Listesi.
        /// </summary>
        public static string ServicesList {
            get {
                return ResourceManager.GetString("ServicesList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site Logo.
        /// </summary>
        public static string SiteLogo {
            get {
                return ResourceManager.GetString("SiteLogo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site Durumu.
        /// </summary>
        public static string SiteStution {
            get {
                return ResourceManager.GetString("SiteStution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site URL.
        /// </summary>
        public static string SiteURL {
            get {
                return ResourceManager.GetString("SiteURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slider Kategorisi.
        /// </summary>
        public static string SliderCategory {
            get {
                return ResourceManager.GetString("SliderCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slider Kategori Listesi.
        /// </summary>
        public static string SliderCategoryList {
            get {
                return ResourceManager.GetString("SliderCategoryList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slider Listesi.
        /// </summary>
        public static string SliderList {
            get {
                return ResourceManager.GetString("SliderList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slider Adı.
        /// </summary>
        public static string SliderName {
            get {
                return ResourceManager.GetString("SliderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slider Fotoğrafı.
        /// </summary>
        public static string SliderPhoto {
            get {
                return ResourceManager.GetString("SliderPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sliders.
        /// </summary>
        public static string Sliders {
            get {
                return ResourceManager.GetString("Sliders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personel Email.
        /// </summary>
        public static string StaffEmail {
            get {
                return ResourceManager.GetString("StaffEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personel Listesi.
        /// </summary>
        public static string StaffList {
            get {
                return ResourceManager.GetString("StaffList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personel Yönetimi.
        /// </summary>
        public static string StaffManagement {
            get {
                return ResourceManager.GetString("StaffManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personel Adı.
        /// </summary>
        public static string StaffName {
            get {
                return ResourceManager.GetString("StaffName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personel Numarası.
        /// </summary>
        public static string StaffNumber {
            get {
                return ResourceManager.GetString("StaffNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personel Görevi.
        /// </summary>
        public static string StaffPosition {
            get {
                return ResourceManager.GetString("StaffPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personel Fotoğrafı.
        /// </summary>
        public static string StaffProfilePhoto {
            get {
                return ResourceManager.GetString("StaffProfilePhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aradığınız data bulunamadı.
        /// </summary>
        public static string Thedatayouarelookingforcouldntfind {
            get {
                return ResourceManager.GetString("Thedatayouarelookingforcouldntfind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Türkçe.
        /// </summary>
        public static string Turkish {
            get {
                return ResourceManager.GetString("Turkish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Türkçe Galeri Adı.
        /// </summary>
        public static string TurkishGalleryName {
            get {
                return ResourceManager.GetString("TurkishGalleryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Türkçe Haber Açıklaması.
        /// </summary>
        public static string TurkishNewsContent {
            get {
                return ResourceManager.GetString("TurkishNewsContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Türkçe Haber Başlığı.
        /// </summary>
        public static string TurkishNewsTitle {
            get {
                return ResourceManager.GetString("TurkishNewsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Türkçe Sayfa İçeriği.
        /// </summary>
        public static string TurkishPageContent {
            get {
                return ResourceManager.GetString("TurkishPageContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Türkçe Sayfa Başlığı.
        /// </summary>
        public static string TurkishPageTitle {
            get {
                return ResourceManager.GetString("TurkishPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Türkçe Ürün Açıklaması.
        /// </summary>
        public static string TurkishProductDescription {
            get {
                return ResourceManager.GetString("TurkishProductDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Türkçe Ürün Adı.
        /// </summary>
        public static string TurkishProductName {
            get {
                return ResourceManager.GetString("TurkishProductName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Türkçe Referans Açıklaması.
        /// </summary>
        public static string TurkishReferenceDescription {
            get {
                return ResourceManager.GetString("TurkishReferenceDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Türkçe Referans Başlığı.
        /// </summary>
        public static string TurkishReferenceTitle {
            get {
                return ResourceManager.GetString("TurkishReferenceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Türkçe Hizmet Açıklaması.
        /// </summary>
        public static string TurkishServiceDescription {
            get {
                return ResourceManager.GetString("TurkishServiceDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Türkçe Hizmet Başlığı.
        /// </summary>
        public static string TurkishServicesTitle {
            get {
                return ResourceManager.GetString("TurkishServicesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Türlçe Slider Başlığı.
        /// </summary>
        public static string TurkishSliderName {
            get {
                return ResourceManager.GetString("TurkishSliderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Güncelle.
        /// </summary>
        public static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yükle.
        /// </summary>
        public static string Upload {
            get {
                return ResourceManager.GetString("Upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Büyük Resim Yükle.
        /// </summary>
        public static string UploadContentPhoto {
            get {
                return ResourceManager.GetString("UploadContentPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Çözüm Otağı Logo Yükle.
        /// </summary>
        public static string UploadPartnerLogo {
            get {
                return ResourceManager.GetString("UploadPartnerLogo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Referans Logosu Yükle.
        /// </summary>
        public static string UploadReferenceLogo {
            get {
                return ResourceManager.GetString("UploadReferenceLogo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slider Fotoğrafları Yüzkle.
        /// </summary>
        public static string UploadSliderPhotos {
            get {
                return ResourceManager.GetString("UploadSliderPhotos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Küçük Resim Yükle.
        /// </summary>
        public static string UploadSmallPhoto {
            get {
                return ResourceManager.GetString("UploadSmallPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personel Fotoğrafı Ekle.
        /// </summary>
        public static string UploadStaffProfilePhoto {
            get {
                return ResourceManager.GetString("UploadStaffProfilePhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcı Menüsü.
        /// </summary>
        public static string UserMenu {
            get {
                return ResourceManager.GetString("UserMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcı Adı.
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcı Yetkisi.
        /// </summary>
        public static string UserRole {
            get {
                return ResourceManager.GetString("UserRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mesajı Görüntüle.
        /// </summary>
        public static string ViewContact {
            get {
                return ResourceManager.GetString("ViewContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ziyaretçi Mesajı.
        /// </summary>
        public static string VisitorMessage {
            get {
                return ResourceManager.GetString("VisitorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Haftaiçi Mesai Saatleri.
        /// </summary>
        public static string WeekdaysWorkingHours {
            get {
                return ResourceManager.GetString("WeekdaysWorkingHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Haftasonu Mesai Saatleri.
        /// </summary>
        public static string WeekendWorkingHours {
            get {
                return ResourceManager.GetString("WeekendWorkingHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hoş Geldiniz.
        /// </summary>
        public static string Wellcome {
            get {
                return ResourceManager.GetString("Wellcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yanlış Parametre.
        /// </summary>
        public static string WrongParameter {
            get {
                return ResourceManager.GetString("WrongParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to var.
        /// </summary>
        public static string Youhave {
            get {
                return ResourceManager.GetString("Youhave", resourceCulture);
            }
        }
    }
}
